const app=document.querySelector('#app');
const stepPlan=[
 ['Preparar el lienzo','Dejá un margen y ubicá la figura completa. Todavía no dibujes detalles.'],
 ['Línea de acción','Trazá una línea muy suave que siga la postura desde la cabeza hasta los pies.'],
 ['Cabeza y eje facial','Dibujá el óvalo de la cabeza y marcá el eje vertical y la línea de los ojos según el giro.'],
 ['Torso y pelvis','Construí la caja del torso y una forma simple para la pelvis. Compará el ancho con la referencia.'],
 ['Brazos y piernas','Marcá hombros, codos, muñecas, caderas, rodillas y tobillos antes de agregar volumen.'],
 ['Volumen del cuerpo','Convertí las líneas de las extremidades en cilindros suaves y corregí las proporciones.'],
 ['Cabello o cabeza','Dibujá primero la silueta completa del cabello; después separá los mechones grandes.'],
 ['Ropa y accesorios','Construí la ropa sobre el cuerpo. Los pliegues deben salir de hombros, codos, cintura y rodillas.'],
 ['Rostro y manos','Agregá ojos, nariz, boca, palmas y dedos. Revisá que las manos se relacionen con los objetos.'],
 ['Lineart','Repasá el contorno exterior con firmeza y usá líneas más finas para ropa, cabello y detalles. Borrá guías.'],
 ['Color base','Coloreá primero piel o pelaje, luego cabello, ropa y accesorios. No pintes encima de las líneas.'],
 ['Sombras y terminación','Aplicá una luz única, agregá sombras debajo del cabello y la ropa, limpiá el fondo y compará con la referencia.']
];
const drawings=[1,2,3,4].map(id=>({id,name:`Dibujo ${id}`,image:`assets/dibujo-${id}.jpg`,steps:stepPlan}));let drawing=1,step=0;
function home(){app.innerHTML=`<section class="home"><div class="hero"><h1>ONE PIECE <span>DRAWING</span></h1><p>Elegí un dibujo y seguí todas sus etapas de construcción.</p></div><div class="rows">${drawings.map(d=>`<article class="row"><div class="num">${d.id}</div><div><h2>${d.name}</h2><div class="steps">${d.steps.map((s,i)=>`<button class="step" data-d="${d.id}" data-s="${i}"><b>${i+1}</b><small>${s[0]}</small></button>`).join('')}</div></div></article>`).join('')}</div></section>`;document.querySelectorAll('[data-d]').forEach(b=>b.onclick=()=>open(+b.dataset.d,+b.dataset.s))}
function drawGuide(ctx,img,n,w,h){ctx.clearRect(0,0,w,h);ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);const scale=Math.min((w-70)/img.width,(h-75)/img.height),iw=img.width*scale,ih=img.height*scale,x=(w-iw)/2,y=(h-ih)/2;ctx.globalAlpha=[.11,.18,.25,.32,.4,.48,.56,.64,.72,.82,.92,1][n];ctx.drawImage(img,x,y,iw,ih);ctx.globalAlpha=1;ctx.strokeStyle='#4c8c9e';ctx.lineWidth=3;ctx.setLineDash([12,10]);ctx.beginPath();ctx.moveTo(w/2,45);ctx.lineTo(w/2,h-45);ctx.stroke();ctx.setLineDash([]);ctx.font='bold 20px system-ui';ctx.fillStyle='#467180';ctx.textAlign='center';ctx.fillText(`GUÍA ${n+1}: ${stepPlan[n][0].toUpperCase()}`,w/2,35)}
function open(id,s){drawing=id;step=s;const d=drawings[id-1],instruction=d.steps[step];app.innerHTML=`<section class="draw"><a class="back" href="#/">← Volver</a><h1>Dibujo ${id} · Paso ${step+1} de ${d.steps.length}</h1><div class="instruction"><strong>Qué dibujar:</strong> ${instruction[1]}</div><div class="board"><canvas id="guide" width="1200" height="750"></canvas><canvas id="paint" width="1200" height="750"></canvas></div><div class="actions"><button class="btn" id="prev" ${step===0?'disabled':''}>← ANTERIOR</button><button class="btn primary" id="next">${step===d.steps.length-1?'TERMINAR':'SEGUIR →'}</button></div></section>`;const guide=document.querySelector('#guide'),g=guide.getContext('2d'),img=new Image();img.onload=()=>drawGuide(g,img,step,guide.width,guide.height);img.src=d.image;const p=document.querySelector('#paint'),ctx=p.getContext('2d');let down=false,last;const point=e=>{const r=p.getBoundingClientRect(),q=e.touches?.[0]||e;return{x:(q.clientX-r.left)*p.width/r.width,y:(q.clientY-r.top)*p.height/r.height}};p.onpointerdown=e=>{down=true;last=point(e)};p.onpointermove=e=>{if(!down)return;const q=point(e);ctx.strokeStyle='#1b3542';ctx.lineWidth=5;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(q.x,q.y);ctx.stroke();last=q};window.onpointerup=()=>down=false;document.querySelector('#prev').onclick=()=>open(id,step-1);document.querySelector('#next').onclick=()=>step<d.steps.length-1?open(id,step+1):home()}home();